### PR TITLE
Add a new test file, and add sorting of text output

### PR DESCRIPTION
**Pull request by d-b-w**
Two commits:
1. Add a new test file, with more unit-like testing of the summary.SummaryReporter.
2. Allow sorting of text output report (https://bitbucket.org/ned/coveragepy/issues/199/add-a-way-to-sort-the-text-report)

### CODE REVIEW

**Comment by nedbat** [comment]
Dan, thanks so much for doing this! I have a few tweaks I'd like to make to this.  Is that something you'd be interested in working on, or should I carry this forward?
1) I'd rather have this configurable from the .coveragerc file, and skip the command-line options.
2) We don't need the version checks in the tests, I have other mechanisms to deal with those issues (backward.py and coveragetest.CoverageTest).

**Comment by d-b-w** [comment]
I'll take a look today. If I can't easily figure out backward.py, I'll pass it back to you.

**Comment by nedbat** [comment]
@d-b-w no worries, I'll get this in shape and merge it.

**Comment by nedbat** [comment]
@d-b-w oh, I missed that you added commits...  Let me see what this looks like now.

**Comment by d-b-w** [comment]
oh - one side effect of this change that I should have mentioned in the commit message - I added TestCase.assertNotIn to backunittest. It becomes available in python2.7.

**Comment by nedbat** [comment]
@d-b-w I noticed that, but I'm using unittest2 on 2.6, so we didn't need to add assertNotIn.  I'm applying this pull request to the BitBucket repo, thanks!

**Comment by nedbat** [comment]
Applied at https://bitbucket.org/ned/coveragepy/commits/86a3c51df06441159c87fc1d69fd9481b19d5be4, cleaned up by https://bitbucket.org/ned/coveragepy/commits/46f163f34fe1deffe1484ea7f7271f659748e833

Thanks so much! Sprints are amazing! :)

**Comment by d-b-w** [comment]
Thanks Ned. I really enjoyed the experience.

**Pull request closed without merging**
