### PR TITLE
#265: Warn and error out when source and include are both used in coverage run

### PR DESCRIPTION
**Pull request by nland**
This addresses issue [#265](https://bitbucket.org/ned/coveragepy/issues/265/when-using-source-include-is-silently), and generates a warning message and errors out. Added a test to ensure that it would return a message and error.

### CODE REVIEW

**Comment by nland** [comment]
ah, sorry the commit from issue #231 was also included in this. disregard as part of the diff.

**Comment by nedbat** [comment]
Thanks for the pull request.  PyCon sprints are amazing! :)

I think we need to also account for other styles of conflicts, like if the .coveragerc file has the include, and the command line has the source, or vice-versa.

**Comment by nedbat** [comment]
@nland I understand if you don't want to work on it beyond the sprints. Just let me know.

**Comment by nedbat** [comment]
This was finished differently in https://bitbucket.org/ned/coveragepy/pull-requests/105/source-and-include-are-mutually-exclusive

**Pull request closed without merging**
