### PR TITLE
Fix integer division inconsistencies between Python 2 and Python 3

### PR DESCRIPTION
**Pull request by rowillia**
Another issue flagged by the `-3` flag.

@nedbat There's still some more clean up to do (in third parties as well) and then we'll be able
to keep this clean with CI :D

### CODE REVIEW

**Comment by nedbat** [comment]
Can you show me the output of your run? One of those files only has float division, so I don't know why `-3` would be complaining.

**Comment by nedbat** [comment]
I've run the coverage.py test suite with the `-3` flag, and I don't get these warnings.

**Comment by rowillia** [comment]
Here's the error I get from running my tests with the `-3` flag in CI:

```
home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coverage/xmlreport.py:188: DeprecationWarning: classic int division
  "%d%% (%d/%d)" % (100*taken/total, taken, total)
```

It actually looks like pylint may have erroneously flagged `results.py`, it looks like that's safely float division.

Here's the output of running all of the coveragepy tests with the `-3` flag.
```shell
rwilliams at rwilliams-mbp114 in ~/src/oss/coveragepy (fix_python2_division●●) (venv)
$ tox -e py27
py27 develop-inst-noop: /Users/rwilliams/src/oss/coveragepy
py27 installed: -e git+git@github.com:rowillia/coveragepy.git@8833e5462cf1c7af16a8d302687b4a4e6690f2ac#egg=coverage,covtestegg1==0.0.0,decorator==4.0.10,eventlet==0.19.0,funcsigs==1.0.2,gevent==1.1.2,greenlet==0.4.10,mock==2.0.0,nose==1.3.7,pbr==1.10.0,PyContracts==1.7.9,pyparsing==2.1.9,six==1.10.0,unittest-mixins==1.1.1
py27 runtests: PYTHONHASHSEED='179065915'
py27 runtests: commands[0] | python setup.py --quiet clean develop
warning: no previously-included files found matching 'ci/appveyor.token'
no previously-included directories found matching 'doc/_build'
no previously-included directories found matching 'tests/eggsrc/dist'
no previously-included directories found matching 'tests/eggsrc/*.egg-info'
py27 runtests: commands[1] | python igor.py zip_mods install_egg remove_extension
py27 runtests: commands[2] | python -3 igor.py test_with_tracer py
=== CPython 2.7.12 with Python tracer (.tox/py27/bin/python) ===
/Users/rwilliams/src/oss/coveragepy/.tox/py27/lib/python2.7/site-packages/nose/plugins/prof.py:14: DeprecationWarning: The 'hotshot' module is not supported in 3.x, use the 'profile' module instead.
  import hotshot
/Users/rwilliams/src/oss/coveragepy/.tox/py27/lib/python2.7/abc.py:87: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
/Users/rwilliams/src/oss/coveragepy/.tox/py27/lib/python2.7/site-packages/contracts/docstring_parsing.py:4: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class Arg(object):
/Users/rwilliams/src/oss/coveragepy/.tox/py27/lib/python2.7/site-packages/contracts/docstring_parsing.py:21: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class DocStringInfo(object):
/Users/rwilliams/src/oss/coveragepy/.tox/py27/lib/python2.7/site-packages/nose/pyversion.py:49: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class Key(object):
/Users/rwilliams/src/oss/coveragepy/.tox/py27/lib/python2.7/site-packages/mock/mock.py:2048: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class _ANY(object):
/Users/rwilliams/src/oss/coveragepy/.tox/py27/lib/python2.7/site-packages/mock/mock.py:2089: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class _Call(tuple):
..............S..S..............................SSS.........................................S................S.......................................................................................................................................................S......................................................................................../Users/rwilliams/src/oss/coveragepy/tests/test_farm.py:122: DeprecationWarning: execfile() not supported in 3.x; use exec()
  execfile(self.runpy, glo)
.................................S..............................................................................................SSSSSSSSSSSSSSSSSSS.............................................................S.................................S..........................................................................
----------------------------------------------------------------------
Ran 667 tests in 73.523s

OK (SKIP=30)
py27 runtests: commands[3] | python setup.py --quiet build_ext --inplace
py27 runtests: commands[4] | python -3 igor.py test_with_tracer c
=== CPython 2.7.12 with C tracer (.tox/py27/bin/python) ===
/Users/rwilliams/src/oss/coveragepy/.tox/py27/lib/python2.7/site-packages/nose/plugins/prof.py:14: DeprecationWarning: The 'hotshot' module is not supported in 3.x, use the 'profile' module instead.
  import hotshot
/Users/rwilliams/src/oss/coveragepy/.tox/py27/lib/python2.7/abc.py:87: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
/Users/rwilliams/src/oss/coveragepy/.tox/py27/lib/python2.7/site-packages/contracts/docstring_parsing.py:4: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class Arg(object):
/Users/rwilliams/src/oss/coveragepy/.tox/py27/lib/python2.7/site-packages/contracts/docstring_parsing.py:21: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class DocStringInfo(object):
/Users/rwilliams/src/oss/coveragepy/.tox/py27/lib/python2.7/site-packages/nose/pyversion.py:49: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class Key(object):
/Users/rwilliams/src/oss/coveragepy/.tox/py27/lib/python2.7/site-packages/mock/mock.py:2048: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class _ANY(object):
/Users/rwilliams/src/oss/coveragepy/.tox/py27/lib/python2.7/site-packages/mock/mock.py:2089: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class _Call(tuple):
..............S..S..............................SSS.........................................S................S.......................................................................................................................................................S......................................................................................../Users/rwilliams/src/oss/coveragepy/tests/test_farm.py:122: DeprecationWarning: execfile() not supported in 3.x; use exec()
  execfile(self.runpy, glo)
.................................S..............................................................................................FF...F....F...................S.................................................S.................................S..........................................................................
======================================================================
FAIL: test_dynamic_source_filename_fails (tests.test_plugins.BadPluginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rwilliams/src/oss/coveragepy/tests/test_plugins.py", line 720, in test_dynamic_source_filename_fails
    self.run_bad_plugin("bad_plugin", "Plugin")
  File "/Users/rwilliams/src/oss/coveragepy/tests/test_plugins.py", line 568, in run_bad_plugin
    self.assertEqual(errors, 1)
AssertionError: 2 != 1
-------------------- >> begin captured stdout << ---------------------
/private/var/folders/b9/gkxhpvdn5ln0z9xb7j39nq140000gp/T/test_cover_38353411/bad_plugin.py:11: DeprecationWarning: classic int division
  101/0 # Oh noes!
Traceback (most recent call last):
  File "/private/var/folders/b9/gkxhpvdn5ln0z9xb7j39nq140000gp/T/test_cover_38353411/bad_plugin.py", line 11, in dynamic_source_filename
    101/0 # Oh noes!
ZeroDivisionError: integer division or modulo by zero
Coverage.py warning: Disabling plugin 'bad_plugin.Plugin' due to previous exception


--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: test_file_tracer_fails (tests.test_plugins.BadPluginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rwilliams/src/oss/coveragepy/tests/test_plugins.py", line 641, in test_file_tracer_fails
    self.run_bad_plugin("bad_plugin", "Plugin")
  File "/Users/rwilliams/src/oss/coveragepy/tests/test_plugins.py", line 568, in run_bad_plugin
    self.assertEqual(errors, 1)
AssertionError: 2 != 1
-------------------- >> begin captured stdout << ---------------------
/private/var/folders/b9/gkxhpvdn5ln0z9xb7j39nq140000gp/T/test_cover_61992019/bad_plugin.py:4: DeprecationWarning: classic int division
  17/0 # Oh noes!
Coverage.py warning: Disabling plugin 'bad_plugin.Plugin' due to an exception:
Traceback (most recent call last):
  File "/Users/rwilliams/src/oss/coveragepy/coverage/control.py", line 527, in _should_trace_internal
    file_tracer = plugin.file_tracer(canonical)
  File "/private/var/folders/b9/gkxhpvdn5ln0z9xb7j39nq140000gp/T/test_cover_61992019/bad_plugin.py", line 4, in file_tracer
    17/0 # Oh noes!
ZeroDivisionError: integer division or modulo by zero


--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: test_has_dynamic_source_filename_fails (tests.test_plugins.BadPluginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rwilliams/src/oss/coveragepy/tests/test_plugins.py", line 669, in test_has_dynamic_source_filename_fails
    self.run_bad_plugin("bad_plugin", "Plugin")
  File "/Users/rwilliams/src/oss/coveragepy/tests/test_plugins.py", line 568, in run_bad_plugin
    self.assertEqual(errors, 1)
AssertionError: 2 != 1
-------------------- >> begin captured stdout << ---------------------
/private/var/folders/b9/gkxhpvdn5ln0z9xb7j39nq140000gp/T/test_cover_49720300/bad_plugin.py:8: DeprecationWarning: classic int division
  23/0 # Oh noes!
Coverage.py warning: Disabling plugin 'bad_plugin.Plugin' due to an exception:
Traceback (most recent call last):
  File "/Users/rwilliams/src/oss/coveragepy/coverage/control.py", line 532, in _should_trace_internal
    if file_tracer.has_dynamic_source_filename():
  File "/private/var/folders/b9/gkxhpvdn5ln0z9xb7j39nq140000gp/T/test_cover_49720300/bad_plugin.py", line 8, in has_dynamic_source_filename
    23/0 # Oh noes!
ZeroDivisionError: integer division or modulo by zero


--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: test_source_filename_fails (tests.test_plugins.BadPluginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rwilliams/src/oss/coveragepy/tests/test_plugins.py", line 685, in test_source_filename_fails
    self.run_bad_plugin("bad_plugin", "Plugin")
  File "/Users/rwilliams/src/oss/coveragepy/tests/test_plugins.py", line 568, in run_bad_plugin
    self.assertEqual(errors, 1)
AssertionError: 2 != 1
-------------------- >> begin captured stdout << ---------------------
/private/var/folders/b9/gkxhpvdn5ln0z9xb7j39nq140000gp/T/test_cover_77978409/bad_plugin.py:8: DeprecationWarning: classic int division
  42/0 # Oh noes!
Coverage.py warning: Disabling plugin 'bad_plugin.Plugin' due to an exception:
Traceback (most recent call last):
  File "/Users/rwilliams/src/oss/coveragepy/coverage/control.py", line 536, in _should_trace_internal
    file_tracer.source_filename()
  File "/private/var/folders/b9/gkxhpvdn5ln0z9xb7j39nq140000gp/T/test_cover_77978409/bad_plugin.py", line 8, in source_filename
    42/0 # Oh noes!
ZeroDivisionError: integer division or modulo by zero


--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 667 tests in 72.457s

FAILED (SKIP=12, failures=4)
ERROR: InvocationError: '/Users/rwilliams/src/oss/coveragepy/.tox/py27/bin/python -3 igor.py test_with_tracer c'
________________________________________________________________________________________________ summary ________________________________________________________________________________________________
ERROR:   py27: commands failed
```

**Comment by nedbat** [comment]
I wish I could get the warning in my own test suite. I don't understand why I don't.  As you see from running the coverage.py suite yourself, the warnings don't appear. :(

**Comment by rowillia** [comment]
@nedbat Agreed.  Filed http://bugs.python.org/issue28288 to make this easier to run without modifying the underlying test runners.

**Comment by nedbat** [comment]
That isn't my point. I did what you did: I edited tox.ini to add the -3 flag to my python invocation. And I saw the same warnings you did, for nose, contracts, and mock. None for coverage.py.  Why does your test suite show a warning for coverage.py, but coverage.py's test suite does not?

**Comment by nedbat** [comment]
I even added a line before the line in xmlreport.py that does integer division, to see what values are being divided to produce what result, and to see that the line is even being executed in my test suite:
```
======================================================================
ERROR: test_y_xml_branch (tests.test_xml.XmlGoldTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ned/coverage/trunk/tests/test_xml.py", line 365, in test_y_xml_branch
    cov.xml_report(y, outfile="../out/y_xml_branch/coverage.xml")
  File "/Users/ned/coverage/trunk/coverage/control.py", line 1096, in xml_report
    return reporter.report(morfs, outfile=outfile)
  File "/Users/ned/coverage/trunk/coverage/xmlreport.py", line 76, in report
    self.report_files(self.xml_file, morfs)
  File "/Users/ned/coverage/trunk/coverage/report.py", line 91, in report_files
    report_fn(fr, self.coverage._analyze(fr))
  File "/Users/ned/coverage/trunk/coverage/xmlreport.py", line 186, in xml_file
    raise Exception("LOOK: %r (%s) and %r (%s) and %r" % (taken, type(taken), total, type(total), 100*taken/total))
Exception: LOOK: 1 (<type 'int'>) and 2 (<type 'int'>) and 50

----------------------------------------------------------------------
Ran 667 tests in 90.114s
```
Still, no warning from `-3`.  I'm not a fan of this feature.

**Comment by nedbat** [comment]
I've changed the division in xmlreport.py to be explicit integer division in https://github.com/nedbat/coveragepy/commit/875201f4cd8566ef98cc1d46b3dffc1ae98a0da9 . Since I didn't have a warning in the first place, I don't know if this will stop the warning you are seeing.  I hope so.

**Comment by rowillia** [comment]
@nedbat Here's a repro:

Clone this repo and https://github.com/rowillia/coverage_py3_warning, and after setting up the venv and installing the requirements run:

```py
python -3 -m pytest
```

As for the usefulness of the `-3` flag, I've been finding this feature to be quite useful when looking at converting a very large codebase that, at times, abuses the dynamic nature of Python.  We really want to get to a point that we have identical output before transitioning, and the `-3` flag is great for identifying problems `2to3` and `python-modernize` can't flag.

**Comment by rowillia** [comment]
Thanks for the fix @nedbat!!

**Pull request closed without merging**
